let beginner = [
    {
        id:1,
        uz_title: "Manzil",
        eng_title: "Address",
        uz_color: "#5F4B8BFF",
        uz_text_color:"#E69A8DFF",
        eng_color: "#42EADDFF",
        eng_text_color:"#CDB599FF",
    },
    {
        id:2,
        uz_title: "Shahar",
        eng_title: "City",
        uz_color: "#000000FF",
        uz_text_color:"#FFFFFFFF",
        eng_color: "#00A4CCFF",
        eng_text_color:"#F95700FF",

    },
    {
        id:3,
        uz_title: "Raqam",
        eng_title: "Number",
        uz_color: "#2C5F2D",
        uz_text_color:"#97BC62FF",
        eng_color: "#00539CFF",
        eng_text_color:"#EEA47FFF",
    },
    {
        id:4,
        uz_title: "Kun",
        eng_title: "Day",
        uz_color: "#0063B2FF",
        uz_text_color:"#9CC3D5FF",
        eng_color: "#D198C5FF",
        eng_text_color:"#E0C568FF",
    },
    {
        id:5,
        uz_title: "Mamlakat",
        eng_title: "Country",
        uz_color: "#B1624EFF",
        uz_text_color:"#5CC8D7FF",
        eng_color: "#89ABE3FF",
        eng_text_color:"#FCF6F5FF",
    },
    {
        id:6,
        uz_title: "Xarita",
        eng_title: "Map",
        uz_color: "#990011FF",
        uz_text_color:"#FCF6F5FF",
        eng_color: "#435E55FF",
        eng_text_color:"#D64161FF",
    },
    {
        id:7,
        uz_title: "Uchrashuv",
        eng_title: "Meeting",
        uz_color: "#CBCE91FF",
        uz_text_color:"#76528BFF",
        eng_color: "#FAEBEFFF",
        eng_text_color:"#333D79FF",
    },
    {
        id:8,
        uz_title: "Ism",
        eng_title: "Name",
        uz_color: "#F93822FF",
        uz_text_color:"#FDD20EFF",
        eng_color: "#F2EDD7FF",
        eng_text_color:"#755139FF",

    },
    {
        id:9,
        uz_title: "Nima",
        eng_title: "What",
        uz_color: "#006B38FF",
        uz_text_color:"#101820FF",
        eng_color: "#FFD662FF",
        eng_text_color:"#00539CFF",
    },
    {
        id:10,
        uz_title: "Olma",
        eng_title: "Apple",
        uz_color: "#00B1D2FF",
        uz_text_color:"#FDDB27FF",
        eng_color: "#E3C9CEFF",
        eng_text_color:"#9FC131FF",
    },
];

