let beginner = [
    {
        id:1,
        uz_title: "Salom",
        eng_title: "Hello",
        uz_color: "#949398FF",
        uz_text_color:"#F4DF4EFF",
        eng_color: "#FC766AFF",
        eng_text_color:"#5B84B1FF",
        uz_trans: "rotate: 40deg",
        eng_trans: "rotate: -85deg",
    },
    {
        id:2,
        uz_title: "Manzil",
        eng_title: "Address",
        uz_color: "#5F4B8BFF",
        uz_text_color:"#E69A8DFF",
        eng_color: "#42EADDFF",
        eng_text_color:"#CDB599FF",
        uz_trans: "rotate: 26deg",
        eng_trans: "rotate: -35deg",
    },
    {
        id:3,
        uz_title: "Shahar",
        eng_title: "City",
        uz_color: "#000000FF",
        uz_text_color:"#FFFFFFFF",
        eng_color: "#00A4CCFF",
        eng_text_color:"#F95700FF",
        uz_trans: "rotate: 13deg",
        eng_trans: "rotate: 21deg",
    },
    {
        id:4,
        uz_title: "Mehmonxona",
        eng_title: "Hotel",
        uz_color: "#00203FFF",
        uz_text_color:"#ADEFD1FF",
        eng_color: "#606060FF",
        eng_text_color:"#D6ED17FF",
        uz_trans: "rotate: 36deg",
        eng_trans: "rotate: 11deg",
    },
    {
        id:5,
        uz_title: "Raqam",
        eng_title: "Number",
        uz_color: "#2C5F2D",
        uz_text_color:"#97BC62FF",
        eng_color: "#00539CFF",
        eng_text_color:"#EEA47FFF",
        uz_trans: "rotate: 300deg",
        eng_trans: "rotate: 50deg",
    },
    {
        id:6,
        uz_title: "Kun",
        eng_title: "Day",
        uz_color: "#0063B2FF",
        uz_text_color:"#9CC3D5FF",
        eng_color: "#D198C5FF",
        eng_text_color:"#E0C568FF",
        uz_trans: "rotate: 320deg",
        eng_trans: "rotate: 20deg",
    },
    {
        id:7,
        uz_title: "Ta'til",
        eng_title: "Holiday",
        uz_color: "#101820FF",
        uz_text_color:"#FEE715FF",
        eng_color: "#CBCE91FF",
        eng_text_color:"#EA738DFF",
        uz_trans: "rotate: 330deg",
        eng_trans: "rotate: 58deg",
    },
    {
        id:8,
        uz_title: "Mamlakat",
        eng_title: "Country",
        uz_color: "#B1624EFF",
        uz_text_color:"#5CC8D7FF",
        eng_color: "#89ABE3FF",
        eng_text_color:"#FCF6F5FF",
        uz_trans: "rotate: 120deg",
        eng_trans: "rotate: 38deg",
    },
    {
        id:9,
        uz_title: "Sakkiz",
        eng_title: "Eight",
        uz_color: "#195190FF",
        uz_text_color:"#A2A2A1FF",
        eng_color: "#603F83FF",
        eng_text_color:"#C7D3D4FF",
        uz_trans: "rotate: 76deg",
        eng_trans: "rotate: 18deg",
    },
    {
        id:10,
        uz_title: "Tanishtirmoq",
        eng_title: "Introduce",
        uz_color: "#2BAE66FF",
        uz_text_color:"#FCF6F5FF",
        eng_color: "#FAD0C9FF",
        eng_text_color:"#6E6E6DFF",
        uz_trans: "rotate: 28deg",
        eng_trans: "rotate: 8deg",
    },
    {
        id:11,
        uz_title: "Ajoyib",
        eng_title: "Fine",
        uz_color: "#2D2926FF",
        uz_text_color:"#E94B3CFF",
        eng_color: "#DAA03DFF",
        eng_text_color:"#616247FF",
        uz_trans: "rotate: 280deg",
        eng_trans: "rotate: 68deg",
    },
    {
        id:12,
        uz_title: "Xarita",
        eng_title: "Map",
        uz_color: "#990011FF",
        uz_text_color:"#FCF6F5FF",
        eng_color: "#435E55FF",
        eng_text_color:"#D64161FF",
        uz_trans: "rotate: 300deg",
        eng_trans: "rotate: 25deg",
    },
    {
        id:13,
        uz_title: "Uchrashuv",
        eng_title: "Meeting",
        uz_color: "#CBCE91FF",
        uz_text_color:"#76528BFF",
        eng_color: "#FAEBEFFF",
        eng_text_color:"#333D79FF",
        uz_trans: "rotate: 333deg",
        eng_trans: "rotate: 87deg",
    },
    {
        id:14,
        uz_title: "Ism",
        eng_title: "Name",
        uz_color: "#F93822FF",
        uz_text_color:"#FDD20EFF",
        eng_color: "#F2EDD7FF",
        eng_text_color:"#755139FF",
        uz_trans: "rotate: 33deg",
        eng_trans: "rotate: 11deg",
    },
    {
        id:15,
        uz_title: "Nima",
        eng_title: "What",
        uz_color: "#006B38FF",
        uz_text_color:"#101820FF",
        eng_color: "#FFD662FF",
        eng_text_color:"#00539CFF",
        uz_trans: "rotate: 78deg",
        eng_trans: "rotate: 290deg",
    },
    {
        id:16,
        uz_title: "Uch",
        eng_title: "Three",
        uz_color: "#D7C49EFF",
        uz_text_color:"#343148FF",
        eng_color: "#FFA177FF",
        eng_text_color:"#F5C7B8FF",
        uz_trans: "rotate: 58deg",
        eng_trans: "rotate: 320deg",
    },
    {
        id:17,
        uz_title: "Turkiya",
        eng_title: "Turkey",
        uz_color: "#DF6589FF",
        uz_text_color:"#3C1053FF",
        eng_color: "#FFE77AFF",
        eng_text_color:"#2C5F2DFF",
        uz_trans: "rotate: 76deg",
        eng_trans: "rotate: 20deg",
    },
    {
        id:18,
        uz_title: "Harflab aytmoq",
        eng_title: "Spell",
        uz_color: "#F1F4FFFF",
        uz_text_color:"#A2A2A1FF",
        eng_color: "#FCF951FF",
        eng_text_color:"#422057FF",
        uz_trans: "rotate: 76deg",
        eng_trans: "rotate: 20deg",
    },
    {
        id:19,
        uz_title: "Haqida",
        eng_title: "About",
        uz_color: "#4B878BFF",
        uz_text_color:"#D01C1FFF",
        eng_color: "#1C1C1BFF",
        eng_text_color:"#CE4A7EFF",
        uz_trans: "rotate: 286deg",
        eng_trans: "rotate: 49deg",
    },
    {
        id:20,
        uz_title: "Olma",
        eng_title: "Apple",
        uz_color: "#00B1D2FF",
        uz_text_color:"#FDDB27FF",
        eng_color: "#E3C9CEFF",
        eng_text_color:"#9FC131FF",
        uz_trans: "rotate: 236deg",
        eng_trans: "rotate: 76deg",
    },
];

